name: wikipedia_api
version: 0.1.0
description: Wikipedia API for dart and flutter
homepage: https://github.com/KRTirtho/wikipedia_api
repository: https://github.com/KRTirtho/wikipedia_api

topics:
  - wikipedia
  - wikipedia-api
  - wikipedia-dart
  - wikipedia-flutter

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  http: ^1.1.0
  meta: ^1.1.8

dev_dependencies:
  test: '>=1.16.0 <1.18.0'
